---
name: Pod-Parser-Groffmom
version: 0.020
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: Convert POD to a format groff_mom can handle.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0.94
  Test::Most: 0.21
requires:
  Moose: 0.6
  Perl6::Junction: 1.4
  Syntax::Highlight::Engine::Kate: 0.06
configure_requires:
  Module::Build: 0.35
provides:
  Pod::Parser::Groffmom:
    file: lib/Pod/Parser/Groffmom.pm
    version: 0.020
  Pod::Parser::Groffmom::Color:
    file: lib/Pod/Parser/Groffmom/Color.pm
    version: 0.020
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
